openapi: 3.0.3
info:
  title: FUEP Post-UTME Portal - Simplified API
  version: '2.0.0'
  description: |
    Comprehensive REST API for candidate and admin workflows, payments, admissions, and system management.

    This API has been significantly simplified and optimized:
    - Streamlined candidate registration and management
    - Unified admin-candidate integration
    - Simplified payment system with direct Remita integration
    - Enhanced performance and maintainability
    - Cleaner interfaces and improved developer experience

security:
  - bearerAuth: []

paths:
  # System health endpoints (mounted at /api/system)
  /api/system:
    get:
      summary: Root system health check
      tags: [System]
      responses:
        '200':
          description: Basic system health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  service: { type: string }
                  timestamp: { type: string, format: date-time }

  /api/system/health:
    get:
      summary: Health check endpoint
      tags: [System]
      responses:
        '200':
          description: Service health status
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string }
                  service: { type: string }
                  timestamp: { type: string, format: date-time }
                  uptime: { type: number }
                  environment: { type: string }

  /api/system/health/db:
    get:
      summary: Database health check
      tags: [System]
      responses:
        '200':
          description: Database connection status
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: object
                    properties:
                      status: { type: string }
                      timestamp: { type: string, format: date-time }

  /api/system/health/detailed:
    get:
      summary: Detailed system health status
      tags: [System]
      responses:
        '200':
          description: Comprehensive system health information
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data:
                    type: object
                    properties:
                      status: { type: string }
                      uptime: { type: number }
                      memory: { type: object }
                      requests: { type: object }
                      database: { type: object }
                      payments: { type: object }
                      timestamp: { type: string, format: date-time }

  # Admin monitoring endpoints
  /api/system/admin/rate-limit-stats:
    get:
      summary: Get rate limiting statistics
      tags: [System, Admin]
      responses:
        '200':
          description: Current rate limiting statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { type: object }

  /api/system/admin/metrics:
    get:
      summary: Get system metrics
      tags: [System, Admin]
      responses:
        '200':
          description: Comprehensive system metrics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { type: object }

  /api/system/admin/cache-stats:
    get:
      summary: Get cache statistics
      tags: [System, Admin]
      responses:
        '200':
          description: Current cache statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  success: { type: boolean }
                  data: { type: object }

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    HealthResponse:
      type: object
      properties:
        status: { type: string }
        service: { type: string }
        timestamp: { type: string, format: date-time }
        uptime: { type: number }
        environment: { type: string }

    SystemHealthResponse:
      type: object
      properties:
        success: { type: boolean }
        data:
          $ref: '#/components/schemas/HealthResponse'
        timestamp: { type: string, format: date-time }

    ErrorResponse:
      type: object
      properties:
        success: { type: boolean }
        error: { type: string }
        timestamp: { type: string, format: date-time }

tags:
  - name: System
    description: System health and monitoring endpoints
