services:
  - type: web
    name: fuep-api
    env: node
    plan: starter
    buildCommand: cd apps/api && npm install && npm run build
    startCommand: cd apps/api && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: fuep-postgres
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: MINIO_ENDPOINT
        value: ${MINIO_ENDPOINT}
      - key: MINIO_ACCESS_KEY
        value: ${MINIO_ACCESS_KEY}
      - key: MINIO_SECRET_KEY
        value: ${MINIO_SECRET_KEY}
      - key: MINIO_USE_SSL
        value: true
      - key: REMITA_PUBLIC_KEY
        value: ${REMITA_PUBLIC_KEY}
      - key: REMITA_SECRET_KEY
        value: ${REMITA_SECRET_KEY}
      - key: REMITA_MERCHANT_ID
        value: ${REMITA_MERCHANT_ID}
      - key: FLUTTERWAVE_PUBLIC_KEY
        value: ${FLUTTERWAVE_PUBLIC_KEY}
      - key: FLUTTERWAVE_SECRET_KEY
        value: ${FLUTTERWAVE_SECRET_KEY}
      - key: SMTP_HOST
        value: ${SMTP_HOST}
      - key: SMTP_PORT
        value: ${SMTP_PORT}
      - key: SMTP_USER
        value: ${SMTP_USER}
      - key: SMTP_PASS
        value: ${SMTP_PASS}
    autoDeploy: true
    scaling:
      minInstances: 1
      maxInstances: 3
      targetCPUPercent: 70
      targetMemoryPercent: 70

databases:
  - name: fuep-postgres
    databaseName: fuep_portal
    user: fuep_user
    plan: starter
